[command]
default=modify_netcdf.py

[mod_netcdf]
add_global_metadata=false
fix_grid_metadata=false
mod_cell_methods=true
netcdf_dir='$ROSE_DATAC'

[model_metadata(all)]
activity_id='EPOC'
branch_method='micro initialisation from CMIP6 macro parent'
branch_time_in_child=0.
branch_time_in_parent=18000.0
contact=
experiment='coupled historical 1950-2014'
experiment_id="hist-1950"
filename_match='*${RUNID}*'
forcing_index='1'
frequency='mon'
further_info_url=
grid_label='gn'
initialization_index='1'
institution='NCAS'
license=''
mip_era='CMIP6'
owner=''
parent_activity_id='HighResMIP'
parent_experiment_id='spinup-1950'
parent_mip_era='CMIP6'
parent_source_id='HadGEM3-GC31-MH'
parent_time_units='days since 1950-01-01'
parent_variant_label='r1i1p1f1'
physics_index='1'
project='Coupled Climate'
realization_index='$ENSEMBLE_NUM'
source='HadGEM3-GC31-HH (2016):
      =aerosol: UKCA-GLOMAP-mode
      =atmos: MetUM-HadGEM3-GA7.1 (N512; 1024 x 768 longitude/latitude; 85 levels; top level 85 km)
      =atmosChem: none
      =land: JULES-HadGEM3-GL7.1
      =landIce: none
      =ocean: NEMO-HadGEM3-GO6.0 (ORCA12 tripolar primarily 1/12 deg; 4320 x 2160 longitude/latitude; 75 levels; top grid cell 0-1 m)
      =ocnBgchem: none
      =seaIce: CICE-HadGEM3-GSI8 (ORCA12 tripolar primarily 1/12 deg; 4320 x 2160 longitude/latitude)'
source_id='HadGEM3-GC31-HH'
source_type='AOGCM'
title='[EPOC] GC3.1 N512 ORCA12 UM11.6'

[model_metadata(atmos)]
external_variables='areacella'
filename_match='*${RUNID}a*'
grid='Native N512 grid; 1024 x 768 longitude/latitude'
nominal_resolution='50 km'
realm='atmos'

[model_metadata(ocean)]
external_variables='areacello'
filename_match='*${RUNID}o*'
grid='Native ORCA12 tripolar primarily 1/12 deg grid; 4320 x 2160 longitude/latitude'
nominal_resolution='10 km'
realm='ocean'

[model_metadata(seaice)]
external_variables='areacello'
filename_match='*${RUNID}i*'
grid='Native ORCA12 tripolar primarily 1/12 deg grid; 4320 x 2160 longitude/latitude'
nominal_resolution='10 km'
realm='seaice'
tracking_id='%uuid%'
