[command]
sort-key=a

[mod_netcdf]
ns=mod_netcdf
title=options
sort-key=b

[model_metadata]
ns=metadata
title=model metadata
duplicate=true
sort-key=c

[mod_netcdf=netcdf_dir]
compulsory=true
description=Source directory of netCDF files.
sort-key=a
type=character

[mod_netcdf=add_global_metadata]
compulsory=true
description=Add global metadata from rose suite file rose-suite.info.
sort-key=b
type=boolean

[mod_netcdf=mod_cell_methods]
compulsory=true
description=Fix cell_methods metadata and time/time bounds data for 
           =monthly means of daily output at different time offset values.
sort-key=c
type=boolean

[mod_netcdf=fix_grid_metadata]
compulsory=true
description=Fix grid metadata for data on rotated pole grids to be cf compliant.
sort-key=d
type=boolean

[model_metadata=filename_match]
compulsory=true
description=Filename matching pattern
type=character

[model_metadata=realization_index]
compulsory=false
description=Ensemble number
